packages:
  - "apps/*"
  - "packages/*"
  - "packages/extensions/*"
  - "packages/templates/*"
  - "packages/tauri-plugins/*"
  - "vendors/tauri-plugin-network"
  - "vendors/tauri-plugin-system-info"
  - "vendors/kkrpc/packages/kkrpc"

