packages:
  - "apps/*"
  - "packages/*"
  - "packages/extensions/*"
  - "packages/templates/*"
  - "packages/tauri-plugins/*"
  - "vendors/tauri-plugin-network"
  - "vendors/tauri-plugin-keyring"
  - "vendors/tauri-plugin-system-info"
  - "vendors/tauri-plugin-user-input"
  - "vendors/kkrpc/packages/kkrpc"

catalog:
  "@tauri-apps/api": ^2.2.0
  "@tauri-apps/cli": ^2.2.2
  "@tauri-apps/plugin-deep-link": ^2.2.0
  "@tauri-apps/plugin-dialog": ^2.2.0
  "@tauri-apps/plugin-fs": ^2.2.0
  "@tauri-apps/plugin-global-shortcut": ^2.2.0
  "@tauri-apps/plugin-http": ^2.2.0
  "@tauri-apps/plugin-log": ^2.2.0
  "@tauri-apps/plugin-notification": ^2.2.0
  "@tauri-apps/plugin-os": ^2.2.0
  "@tauri-apps/plugin-process": 2.2.0
  "@tauri-apps/plugin-shell": ^2.2.0
  "@tauri-apps/plugin-store": ^2.2.0
  "@tauri-apps/plugin-updater": ^2.3.1
  "@tauri-apps/plugin-upload": https://gitpkg.vercel.app/HuakunShen/tauri-plugins-workspace/plugins/upload?69b198b0ccba269fe7622a95ec6a33ae392bff03
  "@tauri-apps/plugin-stronghold": ^2.2.0
  "tauri-plugin-clipboard-api": ^2.1.11
  valibot: ^1.0.0-beta.10
  kkrpc: ^0.0.12
  lodash: ^4.17.21
  svelte-sonner: ^0.3.28
  tauri-api-adapter: ^0.3.16
  tauri-plugin-network-api: 2.0.5
  tauri-plugin-shellx-api: ^2.0.14
  tauri-plugin-system-info-api: 2.0.8
  bits-ui: 1.0.0-next.77
  lucide-svelte: ^0.469.0
  sveltekit-superforms: ^2.22.1
  tailwind-merge: ^2.6.0
  svelte: ^5.16.3
  svelte-radix: ^2.0.1
  clsx: ^2.1.1
  "@kksh/svelte5": ^0.1.10
  "@iconify/svelte": ^4.2.0
  "@types/bun": latest
  tailwind-variants: ^0.3.0
  tailwindcss: ^3.4.17
  tailwindcss-animate: ^1.0.7
  zod: ^3.24.1
  supabase: ^2.2.1
  "@supabase/supabase-js": ^2.47.10
