[package]
name = "tauri-plugin-jarvis"
version = "0.0.0"
authors = ["Huakun"]
description = ""
edition = "2021"
rust-version = "1.70"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-jarvis"

[dependencies]
tauri = { version = "2.0.1" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = "1.0"
applications = { workspace = true }
anyhow = { workspace = true }
tar = "0.4.40"
flate2 = "1.0.30"
window-vibrancy = "0.5.0"
tauri-plugin-store = "2.0.1"
axum = { workspace = true }
axum-extra = { workspace = true }
axum-server = { workspace = true }
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.4.0", features = ["fs", "trace", "cors"] }
tonic = { version = "0.11", features = ["tls"] }
tonic-reflection = "0.11.0"
uuid = { version = "1.8.0", features = ["v4"] }
prost = "0.12"
mime_guess = "2.0.5"
tokio = { workspace = true }
tokio-stream = "0.1.16"
tokio-util = { workspace = true }
mdns-sd = { workspace = true }
reqwest = { workspace = true }
tauri-plugin-network = { workspace = true }
db = { workspace = true }
rustls = { workspace = true }
tauri-plugin-clipboard = { workspace = true }
log = { workspace = true }
strum = { workspace = true }
chrono = { workspace = true }
strum_macros = { workspace = true }
mac-security-rs = { workspace = true }
sysinfo = { workspace = true }
openssl = { workspace = true }
zip = "1.1.4"
rust_search = "2.1.0"
plist = "1.7.0"
crypto = { workspace = true }
base64 = { workspace = true }
obfstr = { workspace = true }
grpc = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
tauri-icns = "0.1.0"

[target.'cfg(target_os = "windows")'.dependencies]
tauri-winres = "0.1.1"
ico = "0.3.0"

[build-dependencies]
tauri-plugin = { version = "2.0.3", features = ["build"] }
tonic-build = "0.11"
base64 = { workspace = true }
