blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/kunkunsh/kunkun/discussions
    about: Please ask and answer questions here.
  - name: 💬 Discord
    url: https://discord.gg/7dzw3TYeTU
    about: Please ask and answer questions here.
