[package]
name = "mac-security-rs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[target.'cfg(target_os = "macos")'.dependencies]
serde = { workspace = true, features = ["derive"] }
core-foundation = "0.10.0"
localauthentication-rs = "0.1.0"
objc = "0.2.7"

[package.metadata]
target_os = "macos"
