[package]
name = "grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
tonic = { version = "0.11", features = ["tls"] }
prost = "0.12"

[build-dependencies]
tonic-build = "0.11"
