"$schema" = "schemas/schema.json"

[[permission]]
identifier = "allow-all"
description = "This enables all permissions for Jarvis"
commands.allow = [
    "open_devtools",
    "close_devtools",
    "is_devtools_open",
    "toggle_devtools",
    "app_is_dev",
    "open_trash",
    "empty_trash",
    "shutdown",
    "reboot",
    "sleep",
    "toggle_system_appearance",
    "show_desktop",
    "quit_all_apps",
    "sleep_displays",
    "set_volume",
    "turn_volume_up",
    "turn_volume_down",
    "toggle_stage_manager",
    "toggle_bluetooth",
    "toggle_hidden_files",
    "eject_all_disks",
    "logout_user",
    "toggle_mute",
    "mute",
    "unmute",
    "hide_all_apps_except_frontmost",
    "get_selected_files_in_file_explorer",
    "run_apple_script",
    "run_powershell",
    "get_applications",
    "refresh_applications_list",
    "refresh_applications_list_in_bg",
    # "load_manifest",
    # "load_all_extensions",
    "path_exists",
    "start_server",
    "get_server_port",
    "stop_server",
    "restart_server",
    "set_dev_extension_folder",
    "set_extension_folder",
    "server_is_running",
    # File System
    "decompress_tarball",
    "compress_tarball",
    # File Search
    "file_search",
    "unzip",
    # Path
    "get_default_extensions_dir",
    "get_default_extensions_storage_dir",
    "is_window_label_registered",
    "register_extension_window",
    "unregister_extension_window",
    "register_extension_spawned_process",
    "unregister_extension_spawned_process",
    "get_ext_label_map",
    "get_frontmost_app",
    # Database
    "create_extension",
    "get_all_extensions",
    "get_unique_extension_by_identifier",
    "get_unique_extension_by_path",
    "get_all_extensions_by_identifier",
    "delete_extension_by_path",
    "delete_extension_by_ext_id",
    "create_command",
    "get_command_by_id",
    "get_commands_by_ext_id",
    "delete_command_by_id",
    "update_command_by_id",
    "create_extension_data",
    "get_extension_data_by_id",
    "search_extension_data",
    "delete_extension_data_by_id",
    "update_extension_data_by_id",
    # Clipboard
    "add_to_history",
    "get_history",
    # Utils
    "plist_to_json",
    "verify_auth",
    "request_screen_capture_access",
    "check_screen_capture_access",
    "get_peers",
]
