[package]
name = "crypto"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
ring = "0.17.8"
openssl = { workspace = true }
anyhow = { workspace = true }
axum = { workspace = true }
tokio = { workspace = true }
rustls = { workspace = true }
axum-server = { workspace = true }
reqwest = { workspace = true }
aes = "0.8.4"
block-padding = "0.3.3"
cbc = { version = "0.1.2", features = ["alloc"] }
