name: CI
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ./pnpm-lock.yaml
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.27
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Install Dependencies
        run: pnpm install
      - name: Setup
        run: pnpm prepare
      - name: Build
        run: pnpm build
      - name: JS Test
        if: matrix.os == 'ubuntu-24.04'
        run: pnpm test
      - name: Install protobuf (Mac)
        if: matrix.settings.platform == 'macos-14'
        run: |
          brew install protobuf
      - name: Install Protobuf (Ubuntu)
        if: matrix.settings.platform == 'ubuntu-22.04'
        run: |
          sudo apt install -y protobuf-compiler
      - name: Install protoc and openssl for windows
        if: matrix.settings.platform == 'windows-latest'
        run: |
          choco install protoc
          choco install openssl
          echo OPENSSL_DIR='"C:\\Program Files\\OpenSSL-Win64"' >> $env:GITHUB_ENV
          echo OPENSSL_INCLUDE_DIR='"C:\\Program Files\\OpenSSL-Win64\\include"' >> $env:GITHUB_ENV
          echo OPENSSL_LIB_DIR='"C:\\Program Files\\OpenSSL-Win64\\lib"' >> $env:GITHUB_ENV

      - name: Rust Test
        run: cargo test
