name: CI
on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-14, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: pnpm/action-setup@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          cache-dependency-path: ./pnpm-lock.yaml
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.27
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install Dependencies
        run: pnpm install
      - name: Setup
        run: pnpm prepare
      - name: Build
        run: pnpm build
      - name: Test
        run: pnpm test
